/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubeblocks.apps.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubeblocks.apps.models.V1alpha1OpsRequestSpecScriptSpecScriptFrom;
import io.kubeblocks.apps.models.V1alpha1OpsRequestSpecScriptSpecSecret;
import io.kubeblocks.apps.models.V1alpha1OpsRequestSpecScriptSpecSelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * scriptSpec defines the script to be executed.
 */
@ApiModel(description = "scriptSpec defines the script to be executed.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-01T05:38:56.141Z[Etc/UTC]")
public class V1alpha1OpsRequestSpecScriptSpec {
  public static final String SERIALIZED_NAME_COMPONENT_NAME = "componentName";
  @SerializedName(SERIALIZED_NAME_COMPONENT_NAME)
  private String componentName;

  public static final String SERIALIZED_NAME_IMAGE = "image";
  @SerializedName(SERIALIZED_NAME_IMAGE)
  private String image;

  public static final String SERIALIZED_NAME_SCRIPT = "script";
  @SerializedName(SERIALIZED_NAME_SCRIPT)
  private List<String> script = null;

  public static final String SERIALIZED_NAME_SCRIPT_FROM = "scriptFrom";
  @SerializedName(SERIALIZED_NAME_SCRIPT_FROM)
  private V1alpha1OpsRequestSpecScriptSpecScriptFrom scriptFrom;

  public static final String SERIALIZED_NAME_SECRET = "secret";
  @SerializedName(SERIALIZED_NAME_SECRET)
  private V1alpha1OpsRequestSpecScriptSpecSecret secret;

  public static final String SERIALIZED_NAME_SELECTOR = "selector";
  @SerializedName(SERIALIZED_NAME_SELECTOR)
  private V1alpha1OpsRequestSpecScriptSpecSelector selector;


  public V1alpha1OpsRequestSpecScriptSpec componentName(String componentName) {
    
    this.componentName = componentName;
    return this;
  }

   /**
   * componentName cluster component name.
   * @return componentName
  **/
  @ApiModelProperty(required = true, value = "componentName cluster component name.")

  public String getComponentName() {
    return componentName;
  }


  public void setComponentName(String componentName) {
    this.componentName = componentName;
  }


  public V1alpha1OpsRequestSpecScriptSpec image(String image) {
    
    this.image = image;
    return this;
  }

   /**
   * exec command with image, by default use the image of kubeblocks-datascript.
   * @return image
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "exec command with image, by default use the image of kubeblocks-datascript.")

  public String getImage() {
    return image;
  }


  public void setImage(String image) {
    this.image = image;
  }


  public V1alpha1OpsRequestSpecScriptSpec script(List<String> script) {
    
    this.script = script;
    return this;
  }

  public V1alpha1OpsRequestSpecScriptSpec addScriptItem(String scriptItem) {
    if (this.script == null) {
      this.script = new ArrayList<>();
    }
    this.script.add(scriptItem);
    return this;
  }

   /**
   * script defines the script to be executed.
   * @return script
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "script defines the script to be executed.")

  public List<String> getScript() {
    return script;
  }


  public void setScript(List<String> script) {
    this.script = script;
  }


  public V1alpha1OpsRequestSpecScriptSpec scriptFrom(V1alpha1OpsRequestSpecScriptSpecScriptFrom scriptFrom) {
    
    this.scriptFrom = scriptFrom;
    return this;
  }

   /**
   * Get scriptFrom
   * @return scriptFrom
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1OpsRequestSpecScriptSpecScriptFrom getScriptFrom() {
    return scriptFrom;
  }


  public void setScriptFrom(V1alpha1OpsRequestSpecScriptSpecScriptFrom scriptFrom) {
    this.scriptFrom = scriptFrom;
  }


  public V1alpha1OpsRequestSpecScriptSpec secret(V1alpha1OpsRequestSpecScriptSpecSecret secret) {
    
    this.secret = secret;
    return this;
  }

   /**
   * Get secret
   * @return secret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1OpsRequestSpecScriptSpecSecret getSecret() {
    return secret;
  }


  public void setSecret(V1alpha1OpsRequestSpecScriptSpecSecret secret) {
    this.secret = secret;
  }


  public V1alpha1OpsRequestSpecScriptSpec selector(V1alpha1OpsRequestSpecScriptSpecSelector selector) {
    
    this.selector = selector;
    return this;
  }

   /**
   * Get selector
   * @return selector
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1OpsRequestSpecScriptSpecSelector getSelector() {
    return selector;
  }


  public void setSelector(V1alpha1OpsRequestSpecScriptSpecSelector selector) {
    this.selector = selector;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1OpsRequestSpecScriptSpec v1alpha1OpsRequestSpecScriptSpec = (V1alpha1OpsRequestSpecScriptSpec) o;
    return Objects.equals(this.componentName, v1alpha1OpsRequestSpecScriptSpec.componentName) &&
        Objects.equals(this.image, v1alpha1OpsRequestSpecScriptSpec.image) &&
        Objects.equals(this.script, v1alpha1OpsRequestSpecScriptSpec.script) &&
        Objects.equals(this.scriptFrom, v1alpha1OpsRequestSpecScriptSpec.scriptFrom) &&
        Objects.equals(this.secret, v1alpha1OpsRequestSpecScriptSpec.secret) &&
        Objects.equals(this.selector, v1alpha1OpsRequestSpecScriptSpec.selector);
  }

  @Override
  public int hashCode() {
    return Objects.hash(componentName, image, script, scriptFrom, secret, selector);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1OpsRequestSpecScriptSpec {\n");
    sb.append("    componentName: ").append(toIndentedString(componentName)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    script: ").append(toIndentedString(script)).append("\n");
    sb.append("    scriptFrom: ").append(toIndentedString(scriptFrom)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    selector: ").append(toIndentedString(selector)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

