/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubeblocks.apps.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubeblocks.apps.models.V1alpha1OpsRequestStatusComponents;
import io.kubeblocks.apps.models.V1alpha1OpsRequestStatusConditions;
import io.kubeblocks.apps.models.V1alpha1OpsRequestStatusLastConfiguration;
import io.kubeblocks.apps.models.V1alpha1OpsRequestStatusReconfiguringStatus;
import io.kubeblocks.apps.models.V1alpha1OpsRequestStatusReconfiguringStatusAsComponent;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * OpsRequestStatus defines the observed state of OpsRequest
 */
@ApiModel(description = "OpsRequestStatus defines the observed state of OpsRequest")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-01T05:38:56.141Z[Etc/UTC]")
public class V1alpha1OpsRequestStatus {
  public static final String SERIALIZED_NAME_CANCEL_TIMESTAMP = "cancelTimestamp";
  @SerializedName(SERIALIZED_NAME_CANCEL_TIMESTAMP)
  private OffsetDateTime cancelTimestamp;

  public static final String SERIALIZED_NAME_CLUSTER_GENERATION = "clusterGeneration";
  @SerializedName(SERIALIZED_NAME_CLUSTER_GENERATION)
  private Long clusterGeneration;

  public static final String SERIALIZED_NAME_COMPLETION_TIMESTAMP = "completionTimestamp";
  @SerializedName(SERIALIZED_NAME_COMPLETION_TIMESTAMP)
  private OffsetDateTime completionTimestamp;

  public static final String SERIALIZED_NAME_COMPONENTS = "components";
  @SerializedName(SERIALIZED_NAME_COMPONENTS)
  private Map<String, V1alpha1OpsRequestStatusComponents> components = null;

  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  private List<V1alpha1OpsRequestStatusConditions> conditions = null;

  public static final String SERIALIZED_NAME_LAST_CONFIGURATION = "lastConfiguration";
  @SerializedName(SERIALIZED_NAME_LAST_CONFIGURATION)
  private V1alpha1OpsRequestStatusLastConfiguration lastConfiguration;

  /**
   * phase describes OpsRequest phase.
   */
  @JsonAdapter(PhaseEnum.Adapter.class)
  public enum PhaseEnum {
    PENDING("Pending"),
    
    CREATING("Creating"),
    
    RUNNING("Running"),
    
    CANCELLING("Cancelling"),
    
    CANCELLED("Cancelled"),
    
    FAILED("Failed"),
    
    SUCCEED("Succeed");

    private String value;

    PhaseEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PhaseEnum fromValue(String value) {
      for (PhaseEnum b : PhaseEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PhaseEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PhaseEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PhaseEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PhaseEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_PHASE = "phase";
  @SerializedName(SERIALIZED_NAME_PHASE)
  private PhaseEnum phase;

  public static final String SERIALIZED_NAME_PROGRESS = "progress";
  @SerializedName(SERIALIZED_NAME_PROGRESS)
  private String progress;

  public static final String SERIALIZED_NAME_RECONFIGURING_STATUS = "reconfiguringStatus";
  @SerializedName(SERIALIZED_NAME_RECONFIGURING_STATUS)
  private V1alpha1OpsRequestStatusReconfiguringStatus reconfiguringStatus;

  public static final String SERIALIZED_NAME_RECONFIGURING_STATUS_AS_COMPONENT = "reconfiguringStatusAsComponent";
  @SerializedName(SERIALIZED_NAME_RECONFIGURING_STATUS_AS_COMPONENT)
  private Map<String, V1alpha1OpsRequestStatusReconfiguringStatusAsComponent> reconfiguringStatusAsComponent = null;

  public static final String SERIALIZED_NAME_START_TIMESTAMP = "startTimestamp";
  @SerializedName(SERIALIZED_NAME_START_TIMESTAMP)
  private OffsetDateTime startTimestamp;


  public V1alpha1OpsRequestStatus cancelTimestamp(OffsetDateTime cancelTimestamp) {
    
    this.cancelTimestamp = cancelTimestamp;
    return this;
  }

   /**
   * CancelTimestamp defines cancel time.
   * @return cancelTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "CancelTimestamp defines cancel time.")

  public OffsetDateTime getCancelTimestamp() {
    return cancelTimestamp;
  }


  public void setCancelTimestamp(OffsetDateTime cancelTimestamp) {
    this.cancelTimestamp = cancelTimestamp;
  }


  public V1alpha1OpsRequestStatus clusterGeneration(Long clusterGeneration) {
    
    this.clusterGeneration = clusterGeneration;
    return this;
  }

   /**
   * ClusterGeneration records the cluster generation after handling the opsRequest action.
   * @return clusterGeneration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ClusterGeneration records the cluster generation after handling the opsRequest action.")

  public Long getClusterGeneration() {
    return clusterGeneration;
  }


  public void setClusterGeneration(Long clusterGeneration) {
    this.clusterGeneration = clusterGeneration;
  }


  public V1alpha1OpsRequestStatus completionTimestamp(OffsetDateTime completionTimestamp) {
    
    this.completionTimestamp = completionTimestamp;
    return this;
  }

   /**
   * completionTimestamp defines the OpsRequest completion time.
   * @return completionTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "completionTimestamp defines the OpsRequest completion time.")

  public OffsetDateTime getCompletionTimestamp() {
    return completionTimestamp;
  }


  public void setCompletionTimestamp(OffsetDateTime completionTimestamp) {
    this.completionTimestamp = completionTimestamp;
  }


  public V1alpha1OpsRequestStatus components(Map<String, V1alpha1OpsRequestStatusComponents> components) {
    
    this.components = components;
    return this;
  }

  public V1alpha1OpsRequestStatus putComponentsItem(String key, V1alpha1OpsRequestStatusComponents componentsItem) {
    if (this.components == null) {
      this.components = new HashMap<>();
    }
    this.components.put(key, componentsItem);
    return this;
  }

   /**
   * components defines the recorded the status information of changed components for operation request.
   * @return components
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "components defines the recorded the status information of changed components for operation request.")

  public Map<String, V1alpha1OpsRequestStatusComponents> getComponents() {
    return components;
  }


  public void setComponents(Map<String, V1alpha1OpsRequestStatusComponents> components) {
    this.components = components;
  }


  public V1alpha1OpsRequestStatus conditions(List<V1alpha1OpsRequestStatusConditions> conditions) {
    
    this.conditions = conditions;
    return this;
  }

  public V1alpha1OpsRequestStatus addConditionsItem(V1alpha1OpsRequestStatusConditions conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * conditions describes opsRequest detail status.
   * @return conditions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "conditions describes opsRequest detail status.")

  public List<V1alpha1OpsRequestStatusConditions> getConditions() {
    return conditions;
  }


  public void setConditions(List<V1alpha1OpsRequestStatusConditions> conditions) {
    this.conditions = conditions;
  }


  public V1alpha1OpsRequestStatus lastConfiguration(V1alpha1OpsRequestStatusLastConfiguration lastConfiguration) {
    
    this.lastConfiguration = lastConfiguration;
    return this;
  }

   /**
   * Get lastConfiguration
   * @return lastConfiguration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1OpsRequestStatusLastConfiguration getLastConfiguration() {
    return lastConfiguration;
  }


  public void setLastConfiguration(V1alpha1OpsRequestStatusLastConfiguration lastConfiguration) {
    this.lastConfiguration = lastConfiguration;
  }


  public V1alpha1OpsRequestStatus phase(PhaseEnum phase) {
    
    this.phase = phase;
    return this;
  }

   /**
   * phase describes OpsRequest phase.
   * @return phase
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "phase describes OpsRequest phase.")

  public PhaseEnum getPhase() {
    return phase;
  }


  public void setPhase(PhaseEnum phase) {
    this.phase = phase;
  }


  public V1alpha1OpsRequestStatus progress(String progress) {
    
    this.progress = progress;
    return this;
  }

   /**
   * Get progress
   * @return progress
  **/
  @ApiModelProperty(required = true, value = "")

  public String getProgress() {
    return progress;
  }


  public void setProgress(String progress) {
    this.progress = progress;
  }


  public V1alpha1OpsRequestStatus reconfiguringStatus(V1alpha1OpsRequestStatusReconfiguringStatus reconfiguringStatus) {
    
    this.reconfiguringStatus = reconfiguringStatus;
    return this;
  }

   /**
   * Get reconfiguringStatus
   * @return reconfiguringStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1OpsRequestStatusReconfiguringStatus getReconfiguringStatus() {
    return reconfiguringStatus;
  }


  public void setReconfiguringStatus(V1alpha1OpsRequestStatusReconfiguringStatus reconfiguringStatus) {
    this.reconfiguringStatus = reconfiguringStatus;
  }


  public V1alpha1OpsRequestStatus reconfiguringStatusAsComponent(Map<String, V1alpha1OpsRequestStatusReconfiguringStatusAsComponent> reconfiguringStatusAsComponent) {
    
    this.reconfiguringStatusAsComponent = reconfiguringStatusAsComponent;
    return this;
  }

  public V1alpha1OpsRequestStatus putReconfiguringStatusAsComponentItem(String key, V1alpha1OpsRequestStatusReconfiguringStatusAsComponent reconfiguringStatusAsComponentItem) {
    if (this.reconfiguringStatusAsComponent == null) {
      this.reconfiguringStatusAsComponent = new HashMap<>();
    }
    this.reconfiguringStatusAsComponent.put(key, reconfiguringStatusAsComponentItem);
    return this;
  }

   /**
   * reconfiguringStatus defines the status information of reconfiguring.
   * @return reconfiguringStatusAsComponent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "reconfiguringStatus defines the status information of reconfiguring.")

  public Map<String, V1alpha1OpsRequestStatusReconfiguringStatusAsComponent> getReconfiguringStatusAsComponent() {
    return reconfiguringStatusAsComponent;
  }


  public void setReconfiguringStatusAsComponent(Map<String, V1alpha1OpsRequestStatusReconfiguringStatusAsComponent> reconfiguringStatusAsComponent) {
    this.reconfiguringStatusAsComponent = reconfiguringStatusAsComponent;
  }


  public V1alpha1OpsRequestStatus startTimestamp(OffsetDateTime startTimestamp) {
    
    this.startTimestamp = startTimestamp;
    return this;
  }

   /**
   * startTimestamp The time when the OpsRequest started processing.
   * @return startTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "startTimestamp The time when the OpsRequest started processing.")

  public OffsetDateTime getStartTimestamp() {
    return startTimestamp;
  }


  public void setStartTimestamp(OffsetDateTime startTimestamp) {
    this.startTimestamp = startTimestamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1OpsRequestStatus v1alpha1OpsRequestStatus = (V1alpha1OpsRequestStatus) o;
    return Objects.equals(this.cancelTimestamp, v1alpha1OpsRequestStatus.cancelTimestamp) &&
        Objects.equals(this.clusterGeneration, v1alpha1OpsRequestStatus.clusterGeneration) &&
        Objects.equals(this.completionTimestamp, v1alpha1OpsRequestStatus.completionTimestamp) &&
        Objects.equals(this.components, v1alpha1OpsRequestStatus.components) &&
        Objects.equals(this.conditions, v1alpha1OpsRequestStatus.conditions) &&
        Objects.equals(this.lastConfiguration, v1alpha1OpsRequestStatus.lastConfiguration) &&
        Objects.equals(this.phase, v1alpha1OpsRequestStatus.phase) &&
        Objects.equals(this.progress, v1alpha1OpsRequestStatus.progress) &&
        Objects.equals(this.reconfiguringStatus, v1alpha1OpsRequestStatus.reconfiguringStatus) &&
        Objects.equals(this.reconfiguringStatusAsComponent, v1alpha1OpsRequestStatus.reconfiguringStatusAsComponent) &&
        Objects.equals(this.startTimestamp, v1alpha1OpsRequestStatus.startTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cancelTimestamp, clusterGeneration, completionTimestamp, components, conditions, lastConfiguration, phase, progress, reconfiguringStatus, reconfiguringStatusAsComponent, startTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1OpsRequestStatus {\n");
    sb.append("    cancelTimestamp: ").append(toIndentedString(cancelTimestamp)).append("\n");
    sb.append("    clusterGeneration: ").append(toIndentedString(clusterGeneration)).append("\n");
    sb.append("    completionTimestamp: ").append(toIndentedString(completionTimestamp)).append("\n");
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    lastConfiguration: ").append(toIndentedString(lastConfiguration)).append("\n");
    sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
    sb.append("    progress: ").append(toIndentedString(progress)).append("\n");
    sb.append("    reconfiguringStatus: ").append(toIndentedString(reconfiguringStatus)).append("\n");
    sb.append("    reconfiguringStatusAsComponent: ").append(toIndentedString(reconfiguringStatusAsComponent)).append("\n");
    sb.append("    startTimestamp: ").append(toIndentedString(startTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

