/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubeblocks.apps.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * lastConfiguration records the last configuration before this operation take effected.
 */
@ApiModel(description = "lastConfiguration records the last configuration before this operation take effected.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-01T05:38:56.141Z[Etc/UTC]")
public class V1alpha1OpsRequestStatusLastConfiguration {
  public static final String SERIALIZED_NAME_CLUSTER_VERSION_REF = "clusterVersionRef";
  @SerializedName(SERIALIZED_NAME_CLUSTER_VERSION_REF)
  private String clusterVersionRef;

  public static final String SERIALIZED_NAME_COMPONENTS = "components";
  @SerializedName(SERIALIZED_NAME_COMPONENTS)
  private Map<String, Object> components = null;


  public V1alpha1OpsRequestStatusLastConfiguration clusterVersionRef(String clusterVersionRef) {
    
    this.clusterVersionRef = clusterVersionRef;
    return this;
  }

   /**
   * clusterVersionRef references ClusterVersion name.
   * @return clusterVersionRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "clusterVersionRef references ClusterVersion name.")

  public String getClusterVersionRef() {
    return clusterVersionRef;
  }


  public void setClusterVersionRef(String clusterVersionRef) {
    this.clusterVersionRef = clusterVersionRef;
  }


  public V1alpha1OpsRequestStatusLastConfiguration components(Map<String, Object> components) {
    
    this.components = components;
    return this;
  }

  public V1alpha1OpsRequestStatusLastConfiguration putComponentsItem(String key, Object componentsItem) {
    if (this.components == null) {
      this.components = new HashMap<>();
    }
    this.components.put(key, componentsItem);
    return this;
  }

   /**
   * components records last configuration of the component.
   * @return components
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "components records last configuration of the component.")

  public Map<String, Object> getComponents() {
    return components;
  }


  public void setComponents(Map<String, Object> components) {
    this.components = components;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1OpsRequestStatusLastConfiguration v1alpha1OpsRequestStatusLastConfiguration = (V1alpha1OpsRequestStatusLastConfiguration) o;
    return Objects.equals(this.clusterVersionRef, v1alpha1OpsRequestStatusLastConfiguration.clusterVersionRef) &&
        Objects.equals(this.components, v1alpha1OpsRequestStatusLastConfiguration.components);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clusterVersionRef, components);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1OpsRequestStatusLastConfiguration {\n");
    sb.append("    clusterVersionRef: ").append(toIndentedString(clusterVersionRef)).append("\n");
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

