/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubeblocks.apps.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * secret defines the secret to be used to execute the script. If not specified, the default cluster root credential secret will be used.
 */
@ApiModel(description = "secret defines the secret to be used to execute the script. If not specified, the default cluster root credential secret will be used.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-01T05:38:56.141Z[Etc/UTC]")
public class V1alpha1OpsRequestSpecScriptSpecSecret {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PASSWORD_KEY = "passwordKey";
  @SerializedName(SERIALIZED_NAME_PASSWORD_KEY)
  private String passwordKey;

  public static final String SERIALIZED_NAME_USERNAME_KEY = "usernameKey";
  @SerializedName(SERIALIZED_NAME_USERNAME_KEY)
  private String usernameKey;


  public V1alpha1OpsRequestSpecScriptSpecSecret name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * name is the name of the secret.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "name is the name of the secret.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha1OpsRequestSpecScriptSpecSecret passwordKey(String passwordKey) {
    
    this.passwordKey = passwordKey;
    return this;
  }

   /**
   * passwordKey field is used to specify the password of the secret.
   * @return passwordKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "passwordKey field is used to specify the password of the secret.")

  public String getPasswordKey() {
    return passwordKey;
  }


  public void setPasswordKey(String passwordKey) {
    this.passwordKey = passwordKey;
  }


  public V1alpha1OpsRequestSpecScriptSpecSecret usernameKey(String usernameKey) {
    
    this.usernameKey = usernameKey;
    return this;
  }

   /**
   * usernameKey field is used to specify the username of the secret.
   * @return usernameKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "usernameKey field is used to specify the username of the secret.")

  public String getUsernameKey() {
    return usernameKey;
  }


  public void setUsernameKey(String usernameKey) {
    this.usernameKey = usernameKey;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1OpsRequestSpecScriptSpecSecret v1alpha1OpsRequestSpecScriptSpecSecret = (V1alpha1OpsRequestSpecScriptSpecSecret) o;
    return Objects.equals(this.name, v1alpha1OpsRequestSpecScriptSpecSecret.name) &&
        Objects.equals(this.passwordKey, v1alpha1OpsRequestSpecScriptSpecSecret.passwordKey) &&
        Objects.equals(this.usernameKey, v1alpha1OpsRequestSpecScriptSpecSecret.usernameKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, passwordKey, usernameKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1OpsRequestSpecScriptSpecSecret {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    passwordKey: ").append(toIndentedString(passwordKey)).append("\n");
    sb.append("    usernameKey: ").append(toIndentedString(usernameKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

