/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubeblocks.apps.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubeblocks.apps.models.V1alpha1OpsRequestSpecRestoreFromBackup;
import io.kubeblocks.apps.models.V1alpha1OpsRequestSpecRestoreFromPointInTime;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * cluster RestoreFrom backup or point in time
 */
@ApiModel(description = "cluster RestoreFrom backup or point in time")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-01T05:38:56.141Z[Etc/UTC]")
public class V1alpha1OpsRequestSpecRestoreFrom {
  public static final String SERIALIZED_NAME_BACKUP = "backup";
  @SerializedName(SERIALIZED_NAME_BACKUP)
  private List<V1alpha1OpsRequestSpecRestoreFromBackup> backup = null;

  public static final String SERIALIZED_NAME_POINT_IN_TIME = "pointInTime";
  @SerializedName(SERIALIZED_NAME_POINT_IN_TIME)
  private V1alpha1OpsRequestSpecRestoreFromPointInTime pointInTime;


  public V1alpha1OpsRequestSpecRestoreFrom backup(List<V1alpha1OpsRequestSpecRestoreFromBackup> backup) {
    
    this.backup = backup;
    return this;
  }

  public V1alpha1OpsRequestSpecRestoreFrom addBackupItem(V1alpha1OpsRequestSpecRestoreFromBackup backupItem) {
    if (this.backup == null) {
      this.backup = new ArrayList<>();
    }
    this.backup.add(backupItem);
    return this;
  }

   /**
   * use the backup name and component name for restore, support for multiple components&#39; recovery.
   * @return backup
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "use the backup name and component name for restore, support for multiple components' recovery.")

  public List<V1alpha1OpsRequestSpecRestoreFromBackup> getBackup() {
    return backup;
  }


  public void setBackup(List<V1alpha1OpsRequestSpecRestoreFromBackup> backup) {
    this.backup = backup;
  }


  public V1alpha1OpsRequestSpecRestoreFrom pointInTime(V1alpha1OpsRequestSpecRestoreFromPointInTime pointInTime) {
    
    this.pointInTime = pointInTime;
    return this;
  }

   /**
   * Get pointInTime
   * @return pointInTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1OpsRequestSpecRestoreFromPointInTime getPointInTime() {
    return pointInTime;
  }


  public void setPointInTime(V1alpha1OpsRequestSpecRestoreFromPointInTime pointInTime) {
    this.pointInTime = pointInTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1OpsRequestSpecRestoreFrom v1alpha1OpsRequestSpecRestoreFrom = (V1alpha1OpsRequestSpecRestoreFrom) o;
    return Objects.equals(this.backup, v1alpha1OpsRequestSpecRestoreFrom.backup) &&
        Objects.equals(this.pointInTime, v1alpha1OpsRequestSpecRestoreFrom.pointInTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backup, pointInTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1OpsRequestSpecRestoreFrom {\n");
    sb.append("    backup: ").append(toIndentedString(backup)).append("\n");
    sb.append("    pointInTime: ").append(toIndentedString(pointInTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

