/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubeblocks.dataprotection.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubeblocks.dataprotection.models.V1alpha1RestoreSpecPrepareDataConfigRequiredPolicyForAllPodSelection;
import io.kubeblocks.dataprotection.models.V1alpha1RestoreSpecReadyConfigJobActionTarget;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * Specifies the configuration for a job action.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-05T14:00:51.636603Z[Etc/UTC]")
public class V1alpha1RestoreSpecReadyConfigJobAction {
  public static final String SERIALIZED_NAME_REQUIRED_POLICY_FOR_ALL_POD_SELECTION = "requiredPolicyForAllPodSelection";
  @SerializedName(SERIALIZED_NAME_REQUIRED_POLICY_FOR_ALL_POD_SELECTION)
  private V1alpha1RestoreSpecPrepareDataConfigRequiredPolicyForAllPodSelection requiredPolicyForAllPodSelection;

  public static final String SERIALIZED_NAME_TARGET = "target";
  @SerializedName(SERIALIZED_NAME_TARGET)
  private V1alpha1RestoreSpecReadyConfigJobActionTarget target;

  public V1alpha1RestoreSpecReadyConfigJobAction() {
  }

  public V1alpha1RestoreSpecReadyConfigJobAction requiredPolicyForAllPodSelection(V1alpha1RestoreSpecPrepareDataConfigRequiredPolicyForAllPodSelection requiredPolicyForAllPodSelection) {
    
    this.requiredPolicyForAllPodSelection = requiredPolicyForAllPodSelection;
    return this;
  }

   /**
   * Get requiredPolicyForAllPodSelection
   * @return requiredPolicyForAllPodSelection
  **/
  @jakarta.annotation.Nullable
  public V1alpha1RestoreSpecPrepareDataConfigRequiredPolicyForAllPodSelection getRequiredPolicyForAllPodSelection() {
    return requiredPolicyForAllPodSelection;
  }


  public void setRequiredPolicyForAllPodSelection(V1alpha1RestoreSpecPrepareDataConfigRequiredPolicyForAllPodSelection requiredPolicyForAllPodSelection) {
    this.requiredPolicyForAllPodSelection = requiredPolicyForAllPodSelection;
  }


  public V1alpha1RestoreSpecReadyConfigJobAction target(V1alpha1RestoreSpecReadyConfigJobActionTarget target) {
    
    this.target = target;
    return this;
  }

   /**
   * Get target
   * @return target
  **/
  @jakarta.annotation.Nonnull
  public V1alpha1RestoreSpecReadyConfigJobActionTarget getTarget() {
    return target;
  }


  public void setTarget(V1alpha1RestoreSpecReadyConfigJobActionTarget target) {
    this.target = target;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1RestoreSpecReadyConfigJobAction v1alpha1RestoreSpecReadyConfigJobAction = (V1alpha1RestoreSpecReadyConfigJobAction) o;
    return Objects.equals(this.requiredPolicyForAllPodSelection, v1alpha1RestoreSpecReadyConfigJobAction.requiredPolicyForAllPodSelection) &&
        Objects.equals(this.target, v1alpha1RestoreSpecReadyConfigJobAction.target);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requiredPolicyForAllPodSelection, target);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1RestoreSpecReadyConfigJobAction {\n");
    sb.append("    requiredPolicyForAllPodSelection: ").append(toIndentedString(requiredPolicyForAllPodSelection)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("requiredPolicyForAllPodSelection");
    openapiFields.add("target");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("target");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1alpha1RestoreSpecReadyConfigJobAction
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1alpha1RestoreSpecReadyConfigJobAction.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1alpha1RestoreSpecReadyConfigJobAction is not found in the empty JSON string", V1alpha1RestoreSpecReadyConfigJobAction.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1alpha1RestoreSpecReadyConfigJobAction.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1alpha1RestoreSpecReadyConfigJobAction` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1alpha1RestoreSpecReadyConfigJobAction.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `requiredPolicyForAllPodSelection`
      if (jsonObj.get("requiredPolicyForAllPodSelection") != null && !jsonObj.get("requiredPolicyForAllPodSelection").isJsonNull()) {
        V1alpha1RestoreSpecPrepareDataConfigRequiredPolicyForAllPodSelection.validateJsonObject(jsonObj.getAsJsonObject("requiredPolicyForAllPodSelection"));
      }
      // validate the required field `target`
      V1alpha1RestoreSpecReadyConfigJobActionTarget.validateJsonObject(jsonObj.getAsJsonObject("target"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1alpha1RestoreSpecReadyConfigJobAction.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1alpha1RestoreSpecReadyConfigJobAction' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1alpha1RestoreSpecReadyConfigJobAction> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1alpha1RestoreSpecReadyConfigJobAction.class));

       return (TypeAdapter<T>) new TypeAdapter<V1alpha1RestoreSpecReadyConfigJobAction>() {
           @Override
           public void write(JsonWriter out, V1alpha1RestoreSpecReadyConfigJobAction value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1alpha1RestoreSpecReadyConfigJobAction read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1alpha1RestoreSpecReadyConfigJobAction given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1alpha1RestoreSpecReadyConfigJobAction
  * @throws IOException if the JSON string is invalid with respect to V1alpha1RestoreSpecReadyConfigJobAction
  */
  public static V1alpha1RestoreSpecReadyConfigJobAction fromJson(String jsonString) throws IOException {
    return new JSON().getGson().fromJson(jsonString, V1alpha1RestoreSpecReadyConfigJobAction.class);
  }

 /**
  * Convert an instance of V1alpha1RestoreSpecReadyConfigJobAction to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return new JSON().getGson().toJson(this);
  }
}

