/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubeblocks.dataprotection.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubeblocks.dataprotection.models.V1alpha1ActionSetSpecBackup;
import io.kubeblocks.dataprotection.models.V1alpha1ActionSetSpecRestore;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * ActionSetSpec defines the desired state of ActionSet
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-05T14:02:15.095121Z[Etc/UTC]")
public class V1alpha1ActionSetSpec {
  public static final String SERIALIZED_NAME_BACKUP = "backup";
  @SerializedName(SERIALIZED_NAME_BACKUP)
  private V1alpha1ActionSetSpecBackup backup;

  public static final String SERIALIZED_NAME_BACKUP_TYPE = "backupType";
  @SerializedName(SERIALIZED_NAME_BACKUP_TYPE)
  private String backupType;

  public static final String SERIALIZED_NAME_ENV = "env";
  @SerializedName(SERIALIZED_NAME_ENV)
  private Object env;

  public static final String SERIALIZED_NAME_ENV_FROM = "envFrom";
  @SerializedName(SERIALIZED_NAME_ENV_FROM)
  private Object envFrom;

  public static final String SERIALIZED_NAME_RESTORE = "restore";
  @SerializedName(SERIALIZED_NAME_RESTORE)
  private V1alpha1ActionSetSpecRestore restore;

  public V1alpha1ActionSetSpec() {
  }

  public V1alpha1ActionSetSpec backup(V1alpha1ActionSetSpecBackup backup) {
    
    this.backup = backup;
    return this;
  }

   /**
   * Get backup
   * @return backup
  **/
  @jakarta.annotation.Nullable
  public V1alpha1ActionSetSpecBackup getBackup() {
    return backup;
  }


  public void setBackup(V1alpha1ActionSetSpecBackup backup) {
    this.backup = backup;
  }


  public V1alpha1ActionSetSpec backupType(String backupType) {
    
    this.backupType = backupType;
    return this;
  }

   /**
   * Specifies the backup type. Supported values include:   - &#x60;Full&#x60; for a full backup. - &#x60;Incremental&#x60; back up data that have changed since the last backup (either full or incremental). - &#x60;Differential&#x60; back up data that has changed since the last full backup. - &#x60;Continuous&#x60; back up transaction logs continuously, such as MySQL binlog, PostgreSQL WAL, etc.   Continuous backup is essential for implementing Point-in-Time Recovery (PITR).
   * @return backupType
  **/
  @jakarta.annotation.Nonnull
  public String getBackupType() {
    return backupType;
  }


  public void setBackupType(String backupType) {
    this.backupType = backupType;
  }


  public V1alpha1ActionSetSpec env(Object env) {
    
    this.env = env;
    return this;
  }

   /**
   * Specifies a list of environment variables to be set in the container.
   * @return env
  **/
  @jakarta.annotation.Nullable
  public Object getEnv() {
    return env;
  }


  public void setEnv(Object env) {
    this.env = env;
  }


  public V1alpha1ActionSetSpec envFrom(Object envFrom) {
    
    this.envFrom = envFrom;
    return this;
  }

   /**
   * Specifies a list of sources to populate environment variables in the container. The keys within a source must be a C_IDENTIFIER. Any invalid keys will be reported as an event when the container starts. If a key exists in multiple sources, the value from the last source will take precedence. Any values defined by an Env with a duplicate key will take precedence.   This field cannot be updated.
   * @return envFrom
  **/
  @jakarta.annotation.Nullable
  public Object getEnvFrom() {
    return envFrom;
  }


  public void setEnvFrom(Object envFrom) {
    this.envFrom = envFrom;
  }


  public V1alpha1ActionSetSpec restore(V1alpha1ActionSetSpecRestore restore) {
    
    this.restore = restore;
    return this;
  }

   /**
   * Get restore
   * @return restore
  **/
  @jakarta.annotation.Nullable
  public V1alpha1ActionSetSpecRestore getRestore() {
    return restore;
  }


  public void setRestore(V1alpha1ActionSetSpecRestore restore) {
    this.restore = restore;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1ActionSetSpec v1alpha1ActionSetSpec = (V1alpha1ActionSetSpec) o;
    return Objects.equals(this.backup, v1alpha1ActionSetSpec.backup) &&
        Objects.equals(this.backupType, v1alpha1ActionSetSpec.backupType) &&
        Objects.equals(this.env, v1alpha1ActionSetSpec.env) &&
        Objects.equals(this.envFrom, v1alpha1ActionSetSpec.envFrom) &&
        Objects.equals(this.restore, v1alpha1ActionSetSpec.restore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backup, backupType, env, envFrom, restore);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1ActionSetSpec {\n");
    sb.append("    backup: ").append(toIndentedString(backup)).append("\n");
    sb.append("    backupType: ").append(toIndentedString(backupType)).append("\n");
    sb.append("    env: ").append(toIndentedString(env)).append("\n");
    sb.append("    envFrom: ").append(toIndentedString(envFrom)).append("\n");
    sb.append("    restore: ").append(toIndentedString(restore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("backup");
    openapiFields.add("backupType");
    openapiFields.add("env");
    openapiFields.add("envFrom");
    openapiFields.add("restore");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("backupType");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1alpha1ActionSetSpec
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1alpha1ActionSetSpec.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1alpha1ActionSetSpec is not found in the empty JSON string", V1alpha1ActionSetSpec.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1alpha1ActionSetSpec.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1alpha1ActionSetSpec` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1alpha1ActionSetSpec.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `backup`
      if (jsonObj.get("backup") != null && !jsonObj.get("backup").isJsonNull()) {
        V1alpha1ActionSetSpecBackup.validateJsonObject(jsonObj.getAsJsonObject("backup"));
      }
      if (!jsonObj.get("backupType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `backupType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("backupType").toString()));
      }
      // validate the optional field `restore`
      if (jsonObj.get("restore") != null && !jsonObj.get("restore").isJsonNull()) {
        V1alpha1ActionSetSpecRestore.validateJsonObject(jsonObj.getAsJsonObject("restore"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1alpha1ActionSetSpec.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1alpha1ActionSetSpec' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1alpha1ActionSetSpec> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1alpha1ActionSetSpec.class));

       return (TypeAdapter<T>) new TypeAdapter<V1alpha1ActionSetSpec>() {
           @Override
           public void write(JsonWriter out, V1alpha1ActionSetSpec value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1alpha1ActionSetSpec read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1alpha1ActionSetSpec given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1alpha1ActionSetSpec
  * @throws IOException if the JSON string is invalid with respect to V1alpha1ActionSetSpec
  */
  public static V1alpha1ActionSetSpec fromJson(String jsonString) throws IOException {
    return new JSON().getGson().fromJson(jsonString, V1alpha1ActionSetSpec.class);
  }

 /**
  * Convert an instance of V1alpha1ActionSetSpec to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return new JSON().getGson().toJson(this);
  }
}

