/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.25.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubeblocks.extensions.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubeblocks.extensions.models.V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInnerResources;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-05T14:02:35.998799Z[Etc/UTC]")
public class V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PERSISTENT_VOLUME_ENABLED = "persistentVolumeEnabled";
  @SerializedName(SERIALIZED_NAME_PERSISTENT_VOLUME_ENABLED)
  private Boolean persistentVolumeEnabled;

  public static final String SERIALIZED_NAME_REPLICAS = "replicas";
  @SerializedName(SERIALIZED_NAME_REPLICAS)
  private Integer replicas;

  public static final String SERIALIZED_NAME_RESOURCES = "resources";
  @SerializedName(SERIALIZED_NAME_RESOURCES)
  private V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInnerResources resources;

  public static final String SERIALIZED_NAME_STORAGE_CLASS = "storageClass";
  @SerializedName(SERIALIZED_NAME_STORAGE_CLASS)
  private String storageClass;

  public static final String SERIALIZED_NAME_TOLERATIONS = "tolerations";
  @SerializedName(SERIALIZED_NAME_TOLERATIONS)
  private String tolerations;

  public V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner() {
  }

  public V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Specifies the name of the item.
   * @return name
  **/
  @jakarta.annotation.Nonnull
  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner persistentVolumeEnabled(Boolean persistentVolumeEnabled) {
    
    this.persistentVolumeEnabled = persistentVolumeEnabled;
    return this;
  }

   /**
   * Indicates whether the Persistent Volume is enabled or not.
   * @return persistentVolumeEnabled
  **/
  @jakarta.annotation.Nullable
  public Boolean getPersistentVolumeEnabled() {
    return persistentVolumeEnabled;
  }


  public void setPersistentVolumeEnabled(Boolean persistentVolumeEnabled) {
    this.persistentVolumeEnabled = persistentVolumeEnabled;
  }


  public V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner replicas(Integer replicas) {
    
    this.replicas = replicas;
    return this;
  }

   /**
   * Specifies the number of replicas.
   * @return replicas
  **/
  @jakarta.annotation.Nullable
  public Integer getReplicas() {
    return replicas;
  }


  public void setReplicas(Integer replicas) {
    this.replicas = replicas;
  }


  public V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner resources(V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInnerResources resources) {
    
    this.resources = resources;
    return this;
  }

   /**
   * Get resources
   * @return resources
  **/
  @jakarta.annotation.Nullable
  public V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInnerResources getResources() {
    return resources;
  }


  public void setResources(V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInnerResources resources) {
    this.resources = resources;
  }


  public V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner storageClass(String storageClass) {
    
    this.storageClass = storageClass;
    return this;
  }

   /**
   * Specifies the name of the storage class.
   * @return storageClass
  **/
  @jakarta.annotation.Nullable
  public String getStorageClass() {
    return storageClass;
  }


  public void setStorageClass(String storageClass) {
    this.storageClass = storageClass;
  }


  public V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner tolerations(String tolerations) {
    
    this.tolerations = tolerations;
    return this;
  }

   /**
   * Specifies the tolerations in a JSON array string format.
   * @return tolerations
  **/
  @jakarta.annotation.Nullable
  public String getTolerations() {
    return tolerations;
  }


  public void setTolerations(String tolerations) {
    this.tolerations = tolerations;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner v1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner = (V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner) o;
    return Objects.equals(this.name, v1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner.name) &&
        Objects.equals(this.persistentVolumeEnabled, v1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner.persistentVolumeEnabled) &&
        Objects.equals(this.replicas, v1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner.replicas) &&
        Objects.equals(this.resources, v1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner.resources) &&
        Objects.equals(this.storageClass, v1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner.storageClass) &&
        Objects.equals(this.tolerations, v1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner.tolerations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, persistentVolumeEnabled, replicas, resources, storageClass, tolerations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    persistentVolumeEnabled: ").append(toIndentedString(persistentVolumeEnabled)).append("\n");
    sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    storageClass: ").append(toIndentedString(storageClass)).append("\n");
    sb.append("    tolerations: ").append(toIndentedString(tolerations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("persistentVolumeEnabled");
    openapiFields.add("replicas");
    openapiFields.add("resources");
    openapiFields.add("storageClass");
    openapiFields.add("tolerations");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("name");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner is not found in the empty JSON string", V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the optional field `resources`
      if (jsonObj.get("resources") != null && !jsonObj.get("resources").isJsonNull()) {
        V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInnerResources.validateJsonObject(jsonObj.getAsJsonObject("resources"));
      }
      if ((jsonObj.get("storageClass") != null && !jsonObj.get("storageClass").isJsonNull()) && !jsonObj.get("storageClass").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `storageClass` to be a primitive type in the JSON string but got `%s`", jsonObj.get("storageClass").toString()));
      }
      if ((jsonObj.get("tolerations") != null && !jsonObj.get("tolerations").isJsonNull()) && !jsonObj.get("tolerations").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tolerations` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tolerations").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner.class));

       return (TypeAdapter<T>) new TypeAdapter<V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner>() {
           @Override
           public void write(JsonWriter out, V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner
  * @throws IOException if the JSON string is invalid with respect to V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner
  */
  public static V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner fromJson(String jsonString) throws IOException {
    return new JSON().getGson().fromJson(jsonString, V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner.class);
  }

 /**
  * Convert an instance of V1alpha1AddonSpecDefaultInstallValuesInnerExtrasInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return new JSON().getGson().toJson(this);
  }
}

